### ISSUE TITLE
ArgumentError (given 0, expected 1) with jwt 2.3.0

### ISSUE THREAD

**Issue by januszm** [rylarson/keystores#9]
When loading the application code with `keystores` `0.4.0` and gem `jwt` in version 2.3.0 the following happens:

```
ArgumentError: wrong number of arguments (given 0, expected 1)
ruby/3.0.0/gems/keystores-0.4.0/lib/keystores/jks/pkcs8_key.rb:63:in `block in <class:RSA>'
ruby/3.0.0/gems/jwt-2.3.0/lib/jwt/jwk/rsa.rb:85:in `new'
...
```

It works fine with `jwt` `2.2.2` so a temporary solution is to lock the jwt version to lower than 2.3.0

**Comment by rylarson** [comment]
I probably need to release a major version change that gets rid of the hack to replace the `new` method on the OpenSSL classes. It was originally done to try to preserve OpenSSL API compatibility but it seems to have some unintended consequences.
